calculator: main.o add.o div.o print.o
	g++ main.o add.o div.o print.o -o calculator


main.o: main.cpp
	g++ -c main.cpp

add.o: add.cpp 
	g++ -c add.cpp

div.o: div.cpp
	g++ -c div.cpp

print.o: print.cpp
	g++ -c print.cpp